apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-store-be-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-store-be
  template:
    metadata:
      labels:
        app: book-store-be
    spec:
      containers:
      - name: book-store-be-container
        image: stefanocipriani/book-store-be:0.0.1-SNAPSHOT
        ports:
        - name: bstore-be-port
          containerPort: 7080

---
apiVersion: v1
kind: Service
metadata:
  name: bstore-be-service
spec:
  ports:
  - port: 31071
    nodePort: 31071
    targetPort: bstore-be-port
    protocol: TCP
  selector:
    app: book-store-be
  type: NodePort